const PREFIX = "@@upload/";
export const OPEN_FILE_WINDOW_REQUESTED = `${PREFIX}OPEN_FILE_WINDOW_REQUESTED`;
export const NEW_BOOKS_HAS_ADDED = `${PREFIX}NEW_BOOKS_HAS_ADDED`;
export const BOOK_UPLOAD_STARTED = `${PREFIX}BOOK_UPLOAD_STARTED`;
